name: 'homebrew test'
description: 'homebrew intsall formula test'

input:
  assets_path:
    description: 'asset file path'
    required: true
  formula_repo_url:
    description: 'formula repository path'
    required: true
    

runs:
  using: 'node12'
  main: './dist/index.js'
