name: 'homebrew test'
description: 'homebrew intsall formula test'

input:
  assets_path:
    description: 'asset file path'
    required: true

runs: pwd
  # using: 'node12'
  # main: './dist/index.js'
