name: 'homebrew test'
description: 'homebrew intsall formula test'

input:
  assets_path:
    description: 'asset file path'
    required: true

steps:
  - name: install
    run: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
